class_name EffectIDs

enum {
	NO_EFFECT = 0,
	OFFENSE_UP = 1,
	DEFENSE_UP = 2,
	ACCURACY_UP = 3,
	OFFENSE_DOWN = 4,
	DEFENSE_DOWN = 5,
	ACCURACY_DOWN = 6,
	
	HEAL_AILMENT = 9,
	APPLY_AILMENT_ART = 10,
	APPLY_BURNED = 11,
	APPLY_STUNNED = 12,
	APPLY_FROZEN = 13,
	APPLY_POISONED = 14,
	APPLY_CONFUSED = 15,
	APPLY_EXHAUSTED = 16,
	APPLY_BLINDED = 17,
	APPLY_SHACKLED = 18,
	APPLY_CORRUPTED = 19,
	APPLY_BLESSED = 20,
	
	BOOST_ON_BURNED = 21,
	BOOST_ON_STUNNED = 22,
	BOOST_ON_FROZEN = 23,
	BOOST_ON_POISONED = 24,
	BOOST_ON_CONFUSED = 25,
	BOOST_ON_EXHAUSTED = 26,
	BOOST_ON_BLINDED = 27,
	BOOST_ON_SHACKLED = 28,
	BOOST_ON_CORRUPTED = 29,
	BOOST_ON_BLESSED = 30,
	
	HIGH_CRIT_CHANCE = 50,
	LOW_CRIT_CHANCE = 51,
	EFFECT_BOOST_25 = 52,
	EFFECT_BOOST_50 = 53,
	EFFECT_BOOST_100 = 54,
	REVIVAL_HALF = 55,
	REVIVAL_FULL = 56,
	
	ITEM_RESTORE_VALUE = 100,
	ITEM_RESTORE_PERCENT = 101,
	ITEM_DISH_HEALTH = 102,
	ITEM_DISH_STAMINA = 103,
	ITEM_DISH_STAT = 104,
	ITEM_DAMAGE = 105,
	
	FIELD_CREATE = 200,
	FIELD_DAMAGE_UP = 201,
	FIELD_DAMAGE_DOWN = 202
}
	#INC_BURN_CHANCE = 31,
	#INC_FREEZE_CHANCE = 32,
	#INC_STUN_CHANCE = 33,
	#INC_POISON_CHANCE = 34,
	#INC_BLIND_CHANCE = 35,
	#INC_BLEED_CHANCE = 36,
	#INC_EXHAUST_CHANCE = 37,
	#INC_CONFUSED_CHANCE = 38,
	#INC_KNOCKDOWN_CHANCE = 39
#}
#	PHYS_ATT_BUFF_AUGM = 101,
#	ETHER_ATT_BUFF_AUGM = 102,
#	PHYS_DEF_BUFF_AUGM = 103,
#	ETHER_DEF_BUFF_AUGM = 104,
#	LUCK_BUFF_AUGM = 105,
#	AGILITY_BUFF_AUGM = 106,
#	
#	HP_REGEN = 110,
#	SP_REGEN = 111,
#	}

static func strategy_art_subcategory(art: BattleArt) -> int:
	if art.effects.size() < 0:
		return 0
	var eff_id: int = art.effects[0];
	if eff_id == OFFENSE_UP or eff_id == DEFENSE_UP or eff_id == ACCURACY_UP:
		return 1 # Buff Art
	if eff_id == OFFENSE_DOWN or eff_id == DEFENSE_DOWN or eff_id == ACCURACY_DOWN:
		return 2 # Debuff Art
	return 0 # No effect
